
SQUIRREL=.

sq32:
	$(MAKE) -C squirrel sq32
	$(MAKE) -C sqstdlib sq32
	$(MAKE) -C sq sq32

sqprof:
	$(MAKE) -C squirrel sqprof
	$(MAKE) -C sqstdlib sqprof
	$(MAKE) -C sq sqprof

sq64:
	$(MAKE) -C squirrel sq64
	$(MAKE) -C sqstdlib sq64
	$(MAKE) -C sq sq64

clean:
	$(MAKE) -C squirrel clean
	$(MAKE) -C sqstdlib clean
	$(MAKE) -C sq clean
