import {styleTags, tags as t} from "@lezer/highlight";

export const squirrelHighlight = styleTags({
  "static": t.modifier,
  "for while do if else switch try catch return throw break continue default case": t.controlKeyword,
  "in yield typeof delete instanceof delegate": t.operatorKeyword,
  "local function class extends constructor": t.definitionKeyword,
  "true false": t.bool,
  "this": t.self,
  "null": t.null,
  "Identifier": t.variableName,
  "LineComment": t.lineComment,
  "BlockComment": t.blockComment,
  "String": t.string,
  "Char": t.character,
  "Integer": t.integer,
  "Float": t.float,
  "Escape": t.escape,
  "UpdateOp": t.updateOperator,
  "ArithOp": t.arithmeticOperator,
  "LogicOp": t.logicOperator,
  "BitOp": t.bitwiseOperator,
  "CompareOp": t.compareOperator,
  "Equals": t.definitionOperator,
  "NewSlot": t.definitionOperator,
  ": Vargs": t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ". ::": t.derefOperator,
  ", ;": t.separator,
})
